/**
 * Task #131 — Guided integrity-repair registry.
 *
 * Backs POST /api/admin/integrity/sweep/repair. Each entry maps an
 * integrity-sweep `checkKey` (see integritySweepService) to a server-
 * side repair function that:
 *
 *   - takes the operator-selected sample IDs,
 *   - wraps work in a single transaction PER ID (not one transaction
 *     spanning the whole batch). This is intentional: the API contract
 *     reports a per-ID `{repaired[], skipped[]}` outcome, and a
 *     batch-wide transaction would force every skip/error to roll back
 *     the successful repairs alongside it. Each ID's lookup, asl
 *     insert, and activity_log insert all share one tx; failures are
 *     caught at the per-ID boundary.
 *   - is replay-safe: a second call against an already-fixed DB writes
 *     zero new rows (no asl row, no activity_log entry),
 *   - returns a typed per-ID outcome ({repaired[], skipped[]}).
 *
 * The registry is the conservative safe-set — anything not listed here
 * stays a manual `scripts/integrity/YYYY-MM-DD-*.sql` job.
 *
 * Activity-log marker: every successful repair writes one row with
 * `type = 'integrity_repair'` and `actorUserId = <admin>` so the audit
 * trail can be filtered cleanly.
 *
 * Error surfacing: unexpected exceptions are caught per ID, logged
 * server-side with full context, and returned to the operator as a
 * generic "Repair failed (see server logs for details)" reason rather
 * than the raw DB/driver message. Domain-level skip reasons (state
 * drift, missing draft, ambiguous match, already linked) ARE returned
 * verbatim because they're operator-actionable and contain no internal
 * detail.
 */
import { and, eq, like, sql } from "drizzle-orm";
import {
  db,
  expensesTable,
  billsTable,
  manualJournalEntryDraftsTable,
  accountingSourceLinksTable,
  activityLogTable,
} from "@workspace/db";
import {
  expenseDraftIdempotencyKey,
} from "./expenseDraftService";
import { billDraftIdempotencyKey } from "./billDraftService";
import { logger } from "./logger";

/**
 * Operator-safe message for any unexpected exception thrown inside a
 * per-ID repair. The full error (with stack + context) is logged
 * server-side; the operator UI shows only this stable string so we
 * don't leak DB/driver internals through the audit-trail UI.
 */
const GENERIC_REPAIR_FAILURE =
  "Repair failed (see server logs for details)";

export const INTEGRITY_REPAIR_ACTIVITY_TYPE = "integrity_repair" as const;

export type RepairActor = {
  id: number;
  display: string;
};

export type RepairSkip = {
  id: number;
  reason: string;
};

export type RepairOutcome = {
  repaired: number[];
  skipped: RepairSkip[];
};

export type RepairFn = (
  ids: number[],
  actor: RepairActor,
) => Promise<RepairOutcome>;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function uniqueInts(ids: number[]): number[] {
  const out: number[] = [];
  const seen = new Set<number>();
  for (const raw of ids) {
    const n = Number(raw);
    if (!Number.isInteger(n) || n <= 0) continue;
    if (seen.has(n)) continue;
    seen.add(n);
    out.push(n);
  }
  return out;
}

/**
 * The expense bridge memo always ends with " (expense #<id>)" — see
 * buildMemo in expenseDraftService. We use that as the matching anchor
 * to find an orphaned draft for an expense whose accounting_source_links
 * row is missing.
 */
function expenseMemoSuffix(expenseId: number): string {
  return `(expense #${expenseId})`;
}

/**
 * Bill accrual memo always ends with " (bill #<id>)".
 */
function billMemoSuffix(billId: number): string {
  return `(bill #${billId})`;
}

/**
 * Bill payment memo is generated by buildPaymentMemo as
 * `Payment of bill #${id} — ${vendorName}`. We anchor on the full
 * `Payment of bill #N — ` token (with the em-dash separator) so that
 * bill `#12` cannot accidentally match a draft for bill `#123` —
 * matching on just the `#N` prefix would conflate any IDs sharing a
 * numeric prefix and silently mis-link `accounting_source_links`.
 */
function billPaymentMemoMatch(billId: number): string {
  return `Payment of bill #${billId} — %`;
}

/**
 * Find the single non-posted draft attributable to a source via memo
 * matching. Returns:
 *   - draftId       — exactly one candidate, safe to link
 *   - null + reason — zero or many candidates; caller skips with reason.
 */
type TxLike = Parameters<Parameters<typeof db.transaction>[0]>[0];

async function findUnlinkedDraft(args: {
  tx: TxLike;
  memoPredicate: ReturnType<typeof sql>;
  alreadyLinkedSubquery: ReturnType<typeof sql>;
}): Promise<
  | { draftId: number; reason?: undefined }
  | { draftId: null; reason: string }
> {
  const candidates = await args.tx
    .select({
      id: manualJournalEntryDraftsTable.id,
      status: manualJournalEntryDraftsTable.status,
    })
    .from(manualJournalEntryDraftsTable)
    .where(
      and(
        args.memoPredicate,
        sql`${manualJournalEntryDraftsTable.status} <> 'posted'`,
        sql`${manualJournalEntryDraftsTable.id} NOT IN (${args.alreadyLinkedSubquery})`,
      ),
    );
  if (candidates.length === 0) {
    return {
      draftId: null,
      reason: "No matching unposted draft found by memo lookup",
    };
  }
  if (candidates.length > 1) {
    return {
      draftId: null,
      reason: `Memo lookup matched ${candidates.length} drafts; manual review required`,
    };
  }
  return { draftId: candidates[0]!.id };
}

// ---------------------------------------------------------------------------
// Repair: expense_draft_no_link
// ---------------------------------------------------------------------------

const repairExpenseDraftNoLink: RepairFn = async (rawIds, actor) => {
  const ids = uniqueInts(rawIds);
  const repaired: number[] = [];
  const skipped: RepairSkip[] = [];

  for (const expenseId of ids) {
    try {
      const result = await db.transaction(async (tx) => {
        const [expense] = await tx
          .select()
          .from(expensesTable)
          .where(eq(expensesTable.id, expenseId))
          .limit(1);
        if (!expense) {
          return { skipped: "Expense no longer exists" } as const;
        }
        if (expense.accountingStatus !== "draft_created") {
          return {
            skipped: `Expense accounting_status is now '${expense.accountingStatus}', no longer 'draft_created'`,
          } as const;
        }

        // Already-linked? Replay-safe short-circuit (writes nothing).
        const [existing] = await tx
          .select({ id: accountingSourceLinksTable.id })
          .from(accountingSourceLinksTable)
          .where(
            and(
              eq(accountingSourceLinksTable.sourceType, "expense"),
              eq(accountingSourceLinksTable.sourceId, expenseId),
              eq(accountingSourceLinksTable.eventType, "primary"),
            ),
          )
          .limit(1);
        if (existing) {
          return { noop: true } as const;
        }

        const lookup = await findUnlinkedDraft({
          tx,
          memoPredicate: sql`${manualJournalEntryDraftsTable.memo} LIKE ${"%" + expenseMemoSuffix(expenseId)}`,
          alreadyLinkedSubquery: sql`SELECT ${accountingSourceLinksTable.manualJournalEntryDraftId} FROM ${accountingSourceLinksTable} WHERE ${accountingSourceLinksTable.manualJournalEntryDraftId} IS NOT NULL`,
        });
        if (lookup.draftId == null) {
          return { skipped: lookup.reason } as const;
        }

        await tx.insert(accountingSourceLinksTable).values({
          sourceType: "expense",
          sourceId: expenseId,
          eventType: "primary",
          idempotencyKey: expenseDraftIdempotencyKey(expenseId),
          manualJournalEntryDraftId: lookup.draftId,
          journalEntryId: null,
          createdByUserId: actor.id,
        });

        await tx.insert(activityLogTable).values({
          type: INTEGRITY_REPAIR_ACTIVITY_TYPE,
          description: `Integrity repair: expense_draft_no_link — re-linked expense #${expenseId} to draft #${lookup.draftId}`,
          actor: actor.display,
          actorUserId: actor.id,
          referenceId: expenseId,
          referenceType: "expense",
          metadata: {
            checkKey: "expense_draft_no_link",
            sourceType: "expense",
            sourceId: expenseId,
            manualJournalEntryDraftId: lookup.draftId,
          },
        });

        return { repaired: lookup.draftId } as const;
      });

      if ("repaired" in result) {
        repaired.push(expenseId);
      } else if ("noop" in result) {
        // Already repaired — surface as skipped so the operator sees the
        // outcome was "nothing to do" rather than "we silently fixed it
        // a second time".
        skipped.push({
          id: expenseId,
          reason: "Already linked — no change needed",
        });
      } else {
        skipped.push({ id: expenseId, reason: result.skipped });
      }
    } catch (err) {
      logger.error(
        { err, checkKey: "expense_draft_no_link", expenseId },
        "Integrity repair failed",
      );
      skipped.push({ id: expenseId, reason: GENERIC_REPAIR_FAILURE });
    }
  }

  return { repaired, skipped };
};

// ---------------------------------------------------------------------------
// Repair: bill_accrual_draft_no_link
// ---------------------------------------------------------------------------

const repairBillAccrualDraftNoLink: RepairFn = async (rawIds, actor) => {
  const ids = uniqueInts(rawIds);
  const repaired: number[] = [];
  const skipped: RepairSkip[] = [];

  for (const billId of ids) {
    try {
      const result = await db.transaction(async (tx) => {
        const [bill] = await tx
          .select()
          .from(billsTable)
          .where(eq(billsTable.id, billId))
          .limit(1);
        if (!bill) {
          return { skipped: "Bill no longer exists" } as const;
        }
        if (bill.accountingStatus !== "draft_created") {
          return {
            skipped: `Bill accounting_status is now '${bill.accountingStatus}', no longer 'draft_created'`,
          } as const;
        }

        const [existing] = await tx
          .select({ id: accountingSourceLinksTable.id })
          .from(accountingSourceLinksTable)
          .where(
            and(
              eq(accountingSourceLinksTable.sourceType, "bill"),
              eq(accountingSourceLinksTable.sourceId, billId),
              eq(accountingSourceLinksTable.eventType, "accrual"),
            ),
          )
          .limit(1);
        if (existing) {
          return { noop: true } as const;
        }

        const lookup = await findUnlinkedDraft({
          tx,
          memoPredicate: sql`${manualJournalEntryDraftsTable.memo} LIKE ${"%" + billMemoSuffix(billId)}`,
          alreadyLinkedSubquery: sql`SELECT ${accountingSourceLinksTable.manualJournalEntryDraftId} FROM ${accountingSourceLinksTable} WHERE ${accountingSourceLinksTable.manualJournalEntryDraftId} IS NOT NULL`,
        });
        if (lookup.draftId == null) {
          return { skipped: lookup.reason } as const;
        }

        await tx.insert(accountingSourceLinksTable).values({
          sourceType: "bill",
          sourceId: billId,
          eventType: "accrual",
          idempotencyKey: billDraftIdempotencyKey("accrual", billId),
          manualJournalEntryDraftId: lookup.draftId,
          journalEntryId: null,
          createdByUserId: actor.id,
        });

        await tx.insert(activityLogTable).values({
          type: INTEGRITY_REPAIR_ACTIVITY_TYPE,
          description: `Integrity repair: bill_accrual_draft_no_link — re-linked bill #${billId} accrual to draft #${lookup.draftId}`,
          actor: actor.display,
          actorUserId: actor.id,
          referenceId: billId,
          referenceType: "bill",
          metadata: {
            checkKey: "bill_accrual_draft_no_link",
            sourceType: "bill",
            sourceId: billId,
            eventType: "accrual",
            manualJournalEntryDraftId: lookup.draftId,
          },
        });

        return { repaired: lookup.draftId } as const;
      });

      if ("repaired" in result) {
        repaired.push(billId);
      } else if ("noop" in result) {
        skipped.push({
          id: billId,
          reason: "Already linked — no change needed",
        });
      } else {
        skipped.push({ id: billId, reason: result.skipped });
      }
    } catch (err) {
      logger.error(
        { err, checkKey: "bill_accrual_draft_no_link", billId },
        "Integrity repair failed",
      );
      skipped.push({ id: billId, reason: GENERIC_REPAIR_FAILURE });
    }
  }

  return { repaired, skipped };
};

// ---------------------------------------------------------------------------
// Repair: bill_payment_draft_no_link
// ---------------------------------------------------------------------------

const repairBillPaymentDraftNoLink: RepairFn = async (rawIds, actor) => {
  const ids = uniqueInts(rawIds);
  const repaired: number[] = [];
  const skipped: RepairSkip[] = [];

  for (const billId of ids) {
    try {
      const result = await db.transaction(async (tx) => {
        const [bill] = await tx
          .select()
          .from(billsTable)
          .where(eq(billsTable.id, billId))
          .limit(1);
        if (!bill) {
          return { skipped: "Bill no longer exists" } as const;
        }
        if (bill.accountingPaymentStatus !== "draft_created") {
          return {
            skipped: `Bill accounting_payment_status is now '${bill.accountingPaymentStatus}', no longer 'draft_created'`,
          } as const;
        }

        const [existing] = await tx
          .select({ id: accountingSourceLinksTable.id })
          .from(accountingSourceLinksTable)
          .where(
            and(
              eq(accountingSourceLinksTable.sourceType, "bill"),
              eq(accountingSourceLinksTable.sourceId, billId),
              eq(accountingSourceLinksTable.eventType, "payment"),
            ),
          )
          .limit(1);
        if (existing) {
          return { noop: true } as const;
        }

        const lookup = await findUnlinkedDraft({
          tx,
          memoPredicate: sql`${manualJournalEntryDraftsTable.memo} LIKE ${billPaymentMemoMatch(billId)}`,
          alreadyLinkedSubquery: sql`SELECT ${accountingSourceLinksTable.manualJournalEntryDraftId} FROM ${accountingSourceLinksTable} WHERE ${accountingSourceLinksTable.manualJournalEntryDraftId} IS NOT NULL`,
        });
        if (lookup.draftId == null) {
          return { skipped: lookup.reason } as const;
        }

        await tx.insert(accountingSourceLinksTable).values({
          sourceType: "bill",
          sourceId: billId,
          eventType: "payment",
          idempotencyKey: billDraftIdempotencyKey("payment", billId),
          manualJournalEntryDraftId: lookup.draftId,
          journalEntryId: null,
          createdByUserId: actor.id,
        });

        await tx.insert(activityLogTable).values({
          type: INTEGRITY_REPAIR_ACTIVITY_TYPE,
          description: `Integrity repair: bill_payment_draft_no_link — re-linked bill #${billId} payment to draft #${lookup.draftId}`,
          actor: actor.display,
          actorUserId: actor.id,
          referenceId: billId,
          referenceType: "bill",
          metadata: {
            checkKey: "bill_payment_draft_no_link",
            sourceType: "bill",
            sourceId: billId,
            eventType: "payment",
            manualJournalEntryDraftId: lookup.draftId,
          },
        });

        return { repaired: lookup.draftId } as const;
      });

      if ("repaired" in result) {
        repaired.push(billId);
      } else if ("noop" in result) {
        skipped.push({
          id: billId,
          reason: "Already linked — no change needed",
        });
      } else {
        skipped.push({ id: billId, reason: result.skipped });
      }
    } catch (err) {
      logger.error(
        { err, checkKey: "bill_payment_draft_no_link", billId },
        "Integrity repair failed",
      );
      skipped.push({ id: billId, reason: GENERIC_REPAIR_FAILURE });
    }
  }

  return { repaired, skipped };
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export type IntegrityRepairCheckKey =
  | "expense_draft_no_link"
  | "bill_accrual_draft_no_link"
  | "bill_payment_draft_no_link";

export type IntegrityRepairDescriptor = {
  /** Sweep check key this entry repairs (1:1 with integritySweepService). */
  checkKey: IntegrityRepairCheckKey;
  /** Operator-facing label shown in the confirmation modal. */
  label: string;
  /**
   * Plain-English description of the change the registry will apply.
   * Surfaced in the UI confirmation modal verbatim — keep concise.
   */
  description: string;
  /** Operator-facing label for the entity behind each ID. */
  idLabel: string;
  fn: RepairFn;
};

export const INTEGRITY_REPAIR_REGISTRY: ReadonlyArray<IntegrityRepairDescriptor> = [
  {
    checkKey: "expense_draft_no_link",
    label: "Re-link expense → draft",
    description:
      "Re-creates the missing accounting_source_links row from the existing draft (matched by the draft's memo suffix `(expense #N)`).",
    idLabel: "expense",
    fn: repairExpenseDraftNoLink,
  },
  {
    checkKey: "bill_accrual_draft_no_link",
    label: "Re-link bill accrual → draft",
    description:
      "Re-creates the missing accrual accounting_source_links row from the existing draft (matched by the draft's memo suffix `(bill #N)`).",
    idLabel: "bill",
    fn: repairBillAccrualDraftNoLink,
  },
  {
    checkKey: "bill_payment_draft_no_link",
    label: "Re-link bill payment → draft",
    description:
      "Re-creates the missing payment accounting_source_links row from the existing draft (matched by the draft's memo prefix `Payment of bill #N`).",
    idLabel: "bill",
    fn: repairBillPaymentDraftNoLink,
  },
];

export const INTEGRITY_REPAIR_KEYS: ReadonlyArray<IntegrityRepairCheckKey> =
  INTEGRITY_REPAIR_REGISTRY.map((d) => d.checkKey);

export function getRepairDescriptor(
  checkKey: string,
): IntegrityRepairDescriptor | null {
  return (
    INTEGRITY_REPAIR_REGISTRY.find((d) => d.checkKey === checkKey) ?? null
  );
}

/**
 * Public-safe summary of the registry — what the UI loads to decide
 * which sweep rows get a "Repair…" affordance.
 */
export type IntegrityRepairSummary = {
  checkKey: IntegrityRepairCheckKey;
  label: string;
  description: string;
  idLabel: string;
};

export function describeRegistry(): IntegrityRepairSummary[] {
  return INTEGRITY_REPAIR_REGISTRY.map((d) => ({
    checkKey: d.checkKey,
    label: d.label,
    description: d.description,
    idLabel: d.idLabel,
  }));
}
