import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminRouter from "./admin";
import dashboardRouter from "./dashboard";
import expensesRouter from "./expenses";
import vendorsRouter from "./vendors";
import billsRouter from "./bills";
import receiptsRouter from "./receipts";
import transactionsRouter from "./transactions";
import programsRouter from "./programs";
import approvalsRouter from "./approvals";
import monthEndRouter from "./month-end";
import storageRouter from "./storage";
import aiRouter from "./ai";
import reportsRouter from "./reports";
import creditsRouter from "./credits";
import notificationsRouter from "./notifications";
import accountingRouter from "./accounting";
import coaRouter from "./coa";
import journalEntryExportSchedulesRouter from "./journal-entry-export-schedules";
import remediationRouter from "./remediation";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(dashboardRouter);
router.use(expensesRouter);
router.use(vendorsRouter);
router.use(billsRouter);
router.use(receiptsRouter);
router.use(transactionsRouter);
router.use(programsRouter);
router.use(approvalsRouter);
router.use(monthEndRouter);
router.use(storageRouter);
router.use(aiRouter);
router.use(reportsRouter);
router.use(creditsRouter);
router.use(notificationsRouter);
router.use(accountingRouter);
router.use(coaRouter);
router.use(journalEntryExportSchedulesRouter);
router.use(remediationRouter);

export default router;
