import {
  pgTable,
  text,
  serial,
  integer,
  timestamp,
  date,
  jsonb,
  index,
  uniqueIndex,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import { copilotThreadsTable } from "./copilot_threads";
import { copilotMessagesTable } from "./copilot_messages";
import { agentActionsTable } from "./agent_actions";

/**
 * Step 8 — Posted general-ledger journal entries.
 *
 * This is the system of record for posted accounting activity. Rows here
 * are created only by the controlled posting workflow on top of an
 * already-approved `agent_actions.draft_journal_entry` row.
 *
 * Hard rules enforced by the route layer (and the DB where possible):
 *   - Posting is server-side only and requires admin/approver.
 *   - Posting is idempotent: `agent_action_id` carries a unique partial
 *     index so a second post returns the existing JE rather than creating
 *     a duplicate row.
 *   - We never delete. Mistakes are corrected by inserting a reversing JE
 *     (`reverses_journal_entry_id` self-FK) and flipping the original to
 *     `status='reversed'` with `reversed_by_journal_entry_id` set.
 *   - Every posted JE keeps the full upstream chain: source thread,
 *     assistant message, approving reviewer, agent action id, and an
 *     `evidence_snapshot` JSON capturing what the copilot relied on at
 *     the moment of approval.
 */
export const JOURNAL_ENTRY_STATUSES = ["posted", "reversed"] as const;
export type JournalEntryStatus = (typeof JOURNAL_ENTRY_STATUSES)[number];

export const journalEntriesTable = pgTable(
  "journal_entries",
  {
    id: serial("id").primaryKey(),
    /**
     * Human-readable identifier (e.g. "JE-2026-000001"). Generated by the
     * posting service so journals can be referenced unambiguously in
     * conversation, audits, and exports without leaking internal serial ids.
     */
    entryNo: text("entry_no").notNull(),
    entryDate: date("entry_date").notNull(),
    memo: text("memo").notNull(),

    // Cents arithmetic only — we never store currency as float.
    totalsDebitsCents: integer("totals_debits_cents").notNull(),
    totalsCreditsCents: integer("totals_credits_cents").notNull(),

    status: text("status").notNull().default("posted"),

    // --- Posting attribution -------------------------------------------------
    postedAt: timestamp("posted_at").notNull().defaultNow(),
    postedByUserId: integer("posted_by_user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "restrict" }),

    // --- Linkage back to the copilot/approval chain --------------------------
    /**
     * The agent_action that this JE was posted from. UNIQUE (where not null)
     * so the database itself enforces "one posting per approved draft".
     * Reversal JEs have NULL here — they are not posted from an agent_action.
     */
    agentActionId: integer("agent_action_id").references(
      () => agentActionsTable.id,
      { onDelete: "restrict" },
    ),
    threadId: integer("thread_id").references(() => copilotThreadsTable.id, {
      onDelete: "set null",
    }),
    assistantMessageId: integer("assistant_message_id").references(
      () => copilotMessagesTable.id,
      { onDelete: "set null" },
    ),
    approverUserId: integer("approver_user_id").references(
      () => usersTable.id,
      { onDelete: "restrict" },
    ),
    /**
     * Frozen snapshot of the evidence/payload at the moment of approval.
     * Mirroring this here means later edits to the agent_action (or its
     * evidence) cannot retroactively change what the posted JE was based
     * on — auditors always see the same picture the approver saw.
     */
    evidenceSnapshot: jsonb("evidence_snapshot"),

    // --- Reversal linkage (self-FKs) ----------------------------------------
    /**
     * If this row IS a reversal entry, the JE it reverses.
     */
    reversesJournalEntryId: integer(
      "reverses_journal_entry_id",
    ).references((): AnyPgColumn => journalEntriesTable.id, {
      onDelete: "restrict",
    }),
    /**
     * If this row HAS BEEN reversed, the JE that reverses it. Set on the
     * original at the time of reversal.
     */
    reversedByJournalEntryId: integer(
      "reversed_by_journal_entry_id",
    ).references((): AnyPgColumn => journalEntriesTable.id, {
      onDelete: "restrict",
    }),
    reversalReason: text("reversal_reason"),

    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("journal_entries_entry_no_uniq").on(table.entryNo),
    // Idempotency at the database level: at most one posted JE per agent_action.
    uniqueIndex("journal_entries_agent_action_uniq")
      .on(table.agentActionId)
      .where(sqlNotNull(table.agentActionId)),
    index("journal_entries_status_idx").on(table.status, table.postedAt),
    index("journal_entries_entry_date_idx").on(table.entryDate),
    index("journal_entries_thread_idx").on(table.threadId),
    index("journal_entries_reverses_idx").on(table.reversesJournalEntryId),
  ],
);

// drizzle's `where` for partial unique indexes requires a SQL expression.
// We isolate the helper here to keep the schema file readable.
import { sql } from "drizzle-orm";
function sqlNotNull(col: unknown) {
  return sql`${col} IS NOT NULL`;
}

export type JournalEntryRow = typeof journalEntriesTable.$inferSelect;
export type JournalEntryInsert = typeof journalEntriesTable.$inferInsert;

// ---------------------------------------------------------------------------
// Lines
// ---------------------------------------------------------------------------

export const JOURNAL_ENTRY_LINE_TYPES = ["debit", "credit"] as const;
export type JournalEntryLineType = (typeof JOURNAL_ENTRY_LINE_TYPES)[number];

export const journalEntryLinesTable = pgTable(
  "journal_entry_lines",
  {
    id: serial("id").primaryKey(),
    journalEntryId: integer("journal_entry_id")
      .notNull()
      .references(() => journalEntriesTable.id, { onDelete: "restrict" }),
    lineNo: integer("line_no").notNull(),
    type: text("type").notNull(),
    /**
     * Stored as positive cents on whichever side (`type`) the line is on —
     * NEVER floats. Balance check is `sum(debit cents) == sum(credit cents)`.
     */
    amountCents: integer("amount_cents").notNull(),
    account: text("account").notNull(),
    program: text("program"),
    fund: text("fund"),
    memo: text("memo"),
  },
  (table) => [
    index("journal_entry_lines_je_idx").on(table.journalEntryId, table.lineNo),
    uniqueIndex("journal_entry_lines_je_lineno_uniq").on(
      table.journalEntryId,
      table.lineNo,
    ),
  ],
);

export type JournalEntryLineRow = typeof journalEntryLinesTable.$inferSelect;
export type JournalEntryLineInsert =
  typeof journalEntryLinesTable.$inferInsert;
