import {
  pgTable,
  text,
  serial,
  integer,
  timestamp,
  date,
  jsonb,
  index,
  uniqueIndex,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import { copilotThreadsTable } from "./copilot_threads";
import { copilotMessagesTable } from "./copilot_messages";
import { agentActionsTable } from "./agent_actions";
import { chartOfAccountsTable } from "./chart_of_accounts";

/**
 * Step 8 — Posted general-ledger journal entries.
 *
 * This is the system of record for posted accounting activity. Rows here
 * are created only by the controlled posting workflow on top of an
 * already-approved `agent_actions.draft_journal_entry` row.
 *
 * Hard rules enforced by the route layer (and the DB where possible):
 *   - Posting is server-side only and requires admin/approver.
 *   - Posting is idempotent: `agent_action_id` carries a unique partial
 *     index so a second post returns the existing JE rather than creating
 *     a duplicate row.
 *   - We never delete. Mistakes are corrected by inserting a reversing JE
 *     (`reverses_journal_entry_id` self-FK) and flipping the original to
 *     `status='reversed'` with `reversed_by_journal_entry_id` set.
 *   - Every posted JE keeps the full upstream chain: source thread,
 *     assistant message, approving reviewer, agent action id, and an
 *     `evidence_snapshot` JSON capturing what the copilot relied on at
 *     the moment of approval.
 */
export const JOURNAL_ENTRY_STATUSES = ["posted", "reversed"] as const;
export type JournalEntryStatus = (typeof JOURNAL_ENTRY_STATUSES)[number];

export const journalEntriesTable = pgTable(
  "journal_entries",
  {
    id: serial("id").primaryKey(),
    /**
     * Human-readable identifier (e.g. "JE-2026-000001"). Generated by the
     * posting service so journals can be referenced unambiguously in
     * conversation, audits, and exports without leaking internal serial ids.
     */
    entryNo: text("entry_no").notNull(),
    entryDate: date("entry_date").notNull(),
    memo: text("memo").notNull(),

    // Cents arithmetic only — we never store currency as float.
    totalsDebitsCents: integer("totals_debits_cents").notNull(),
    totalsCreditsCents: integer("totals_credits_cents").notNull(),

    status: text("status").notNull().default("posted"),

    // --- Posting attribution -------------------------------------------------
    postedAt: timestamp("posted_at").notNull().defaultNow(),
    postedByUserId: integer("posted_by_user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "restrict" }),

    // --- Linkage back to the copilot/approval chain --------------------------
    /**
     * The agent_action that this JE was posted from. UNIQUE (where not null)
     * so the database itself enforces "one posting per approved draft".
     * Reversal JEs have NULL here — they are not posted from an agent_action.
     */
    agentActionId: integer("agent_action_id").references(
      () => agentActionsTable.id,
      { onDelete: "restrict" },
    ),
    threadId: integer("thread_id").references(() => copilotThreadsTable.id, {
      onDelete: "set null",
    }),
    assistantMessageId: integer("assistant_message_id").references(
      () => copilotMessagesTable.id,
      { onDelete: "set null" },
    ),
    approverUserId: integer("approver_user_id").references(
      () => usersTable.id,
      { onDelete: "restrict" },
    ),
    /**
     * Frozen snapshot of the evidence/payload at the moment of approval.
     * Mirroring this here means later edits to the agent_action (or its
     * evidence) cannot retroactively change what the posted JE was based
     * on — auditors always see the same picture the approver saw.
     */
    evidenceSnapshot: jsonb("evidence_snapshot"),

    // --- Reversal linkage (self-FKs) ----------------------------------------
    /**
     * If this row IS a reversal entry, the JE it reverses.
     */
    reversesJournalEntryId: integer(
      "reverses_journal_entry_id",
    ).references((): AnyPgColumn => journalEntriesTable.id, {
      onDelete: "restrict",
    }),
    /**
     * If this row HAS BEEN reversed, the JE that reverses it. Set on the
     * original at the time of reversal.
     */
    reversedByJournalEntryId: integer(
      "reversed_by_journal_entry_id",
    ).references((): AnyPgColumn => journalEntriesTable.id, {
      onDelete: "restrict",
    }),
    reversalReason: text("reversal_reason"),

    /**
     * Task 25A — caller-supplied idempotency key for the manual-post path.
     * Required by `POST /accounting/journal-entries`; null for reversals
     * and for legacy/agent-action posts (those have their own idempotency
     * via `agent_action_id`). The DB-level partial unique index below
     * makes "one JE per (idempotency_key)" race-safe — a parallel duplicate
     * insert raises a unique-violation, which the service catches and
     * resolves by returning the existing JE (replay) or 409 (conflict).
     */
    idempotencyKey: text("idempotency_key"),

    /**
     * Task #29B — when this JE was posted from an approved manual
     * journal-entry draft, this column points back at that draft. NULL
     * for direct manual posts (no approval workflow), agent-action
     * posts, and reversals. Together with the matching column on
     * `manual_journal_entry_drafts.posted_journal_entry_id`, a single
     * SQL join recovers the full draft → submit → approve → post chain.
     *
     * Plain integer column with a SQL-level FK added in a follow-up
     * push — drizzle does not let us point at the drafts table here
     * without creating an import cycle, so the relational constraint
     * is enforced by the partial unique index below + application-side
     * checks in postManualJournalEntry. (Cycle could be broken with
     * a `references((): AnyPgColumn => ...)` import-on-use, but that
     * still requires importing the drafts schema, which itself imports
     * this file.)
     */
    manualDraftId: integer("manual_draft_id"),

    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("journal_entries_entry_no_uniq").on(table.entryNo),
    // Idempotency at the database level: at most one posted JE per agent_action.
    uniqueIndex("journal_entries_agent_action_uniq")
      .on(table.agentActionId)
      .where(sqlNotNull(table.agentActionId)),
    // Task 25A — at most one posted JE per caller-supplied idempotency key.
    uniqueIndex("journal_entries_idempotency_key_uniq")
      .on(table.idempotencyKey)
      .where(sqlNotNull(table.idempotencyKey)),
    // Task #29B — at most one posted JE per manual draft (defence in
    // depth on top of the deterministic idempotency key the route uses).
    uniqueIndex("journal_entries_manual_draft_uniq")
      .on(table.manualDraftId)
      .where(sqlNotNull(table.manualDraftId)),
    index("journal_entries_status_idx").on(table.status, table.postedAt),
    index("journal_entries_entry_date_idx").on(table.entryDate),
    index("journal_entries_thread_idx").on(table.threadId),
    index("journal_entries_reverses_idx").on(table.reversesJournalEntryId),
  ],
);

// drizzle's `where` for partial unique indexes requires a SQL expression.
// We isolate the helper here to keep the schema file readable.
import { sql } from "drizzle-orm";
function sqlNotNull(col: unknown) {
  return sql`${col} IS NOT NULL`;
}

export type JournalEntryRow = typeof journalEntriesTable.$inferSelect;
export type JournalEntryInsert = typeof journalEntriesTable.$inferInsert;

// ---------------------------------------------------------------------------
// Lines
// ---------------------------------------------------------------------------

export const JOURNAL_ENTRY_LINE_TYPES = ["debit", "credit"] as const;
export type JournalEntryLineType = (typeof JOURNAL_ENTRY_LINE_TYPES)[number];

export const journalEntryLinesTable = pgTable(
  "journal_entry_lines",
  {
    id: serial("id").primaryKey(),
    journalEntryId: integer("journal_entry_id")
      .notNull()
      .references(() => journalEntriesTable.id, { onDelete: "restrict" }),
    lineNo: integer("line_no").notNull(),
    type: text("type").notNull(),
    /**
     * Stored as positive cents on whichever side (`type`) the line is on —
     * NEVER floats. Balance check is `sum(debit cents) == sum(credit cents)`.
     */
    amountCents: integer("amount_cents").notNull(),
    /**
     * Free-text account string captured at posting time. NEVER mutated
     * — preserves the immutable historical record. Step 9 added the
     * `accountId` FK alongside it; new postings populate both, and the
     * Step 9 backfill populates accountId for historical rows.
     */
    account: text("account").notNull(),
    /**
     * Step 9 — link to the Chart of Accounts. Nullable at the column
     * level because the historical backfill runs after the schema push,
     * and a brand-new install may have rows for a brief window before
     * backfill completes. Posting validation requires this to be non-null
     * for any newly-posted line (enforced in postingService).
     */
    accountId: integer("account_id").references(
      () => chartOfAccountsTable.id,
      { onDelete: "restrict" },
    ),
    program: text("program"),
    fund: text("fund"),
    memo: text("memo"),
  },
  (table) => [
    index("journal_entry_lines_je_idx").on(table.journalEntryId, table.lineNo),
    uniqueIndex("journal_entry_lines_je_lineno_uniq").on(
      table.journalEntryId,
      table.lineNo,
    ),
    index("journal_entry_lines_account_id_idx").on(table.accountId),
  ],
);

export type JournalEntryLineRow = typeof journalEntryLinesTable.$inferSelect;
export type JournalEntryLineInsert =
  typeof journalEntryLinesTable.$inferInsert;
